version: '3.6'

services:
  voting:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET=secret
      - HOST=localhost
      - LDAP_URI=ldap://ldap
      - LDAP_BIND_DN=cn=readonly,dc=example,dc=com
      - LDAP_BIND_PASSWORD=changeme
      - LDAP_USER_BASE=ou=people,dc=example,dc=com
      - LDAP_USER_FILTER=(mail=%(user)s)
      - LDAP_GROUP_BASE=ou=groups,dc=example,dc=com
      - LDAP_STAFF_GROUP=cn=staff,ou=groups,dc=example,dc=com
      - LDAP_SUPERUSER_GROUP=cn=superuser,ou=groups,dc=example,dc=com
  ldap:
    image: osixia/openldap
    restart: always
    environment:
      - LDAP_ORGANISATION=Example Org
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=changeme
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=changeme
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
  ldap_admin:
    image: osixia/phpldapadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - ldap
volumes:
  ldap_data:
  ldap_config:
