# Generated by Django 3.1.2 on 2020-10-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('begin_date', models.DateTimeField(verbose_name='begin date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('ready', models.BooleanField(default=False, verbose_name='ready')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('text_en', models.TextField(null=True, verbose_name='text')),
                ('text_fr', models.TextField(null=True, verbose_name='text')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vote', verbose_name='vote')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('document', models.FileField(upload_to='', verbose_name='document')),
                ('document_en', models.FileField(null=True, upload_to='', verbose_name='document')),
                ('document_fr', models.FileField(null=True, upload_to='', verbose_name='document')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vote', verbose_name='vote')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=255, verbose_name="user's hash")),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vote', verbose_name='vote')),
            ],
            options={
                'verbose_name': 'ballot',
                'verbose_name_plural': 'ballots',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='answer')),
                ('answer_en', models.TextField(null=True, verbose_name='answer')),
                ('answer_fr', models.TextField(null=True, verbose_name='answer')),
                ('number', models.IntegerField(default=0, null=True, verbose_name='number')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='vote')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
    ]
