# Generated by Django 3.1.2 on 2020-12-04 17:28

import hashlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convert(apps, schema_editor):
    """Convert the old values.

    Here, for every hash, we need to get through all the user to find the good one and then assign it to the ballot.
    We also need ot be careful of the language.

    If no user is found, the ballot is deleted. Note that this operation cannot be properly reversed and that ballots may be lost during migration.
    """
    Ballot = apps.get_model("core", "Ballot")
    User = apps.get_model("auth", "User")
    for ballot in Ballot.objects.all():
        vote = ballot.vote
        for language in [l[0] for l in settings.LANGUAGES]:
            if hasattr(vote, "name_{}".format(language)):
                name = getattr(vote, "name_{}".format(language))
                for user in User.objects.all():
                    to_hash = user.username + name
                    if (
                        ballot.user_hash
                        == hashlib.sha224(to_hash.encode("utf-8")).hexdigest()
                    ):
                        ballot.user = user
                        ballot.save()
        if not ballot.user:
            ballot.delete()


def reverse_convert(apps, schema_editor):
    Ballot = apps.get_model("core", "Ballot")
    for ballot in Ballot.objects.all():
        to_hash = ballot.user.username + ballot.vote.name
        ballot.user_hash = hashlib.sha224(to_hash.encode("utf-8")).hexdigest()
        ballot.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.RunPython(convert, reverse_convert),
        migrations.RemoveField(
            model_name="ballot",
            name="user_hash",
        ),
    ]
