# Generated by Django 3.1.2 on 2020-12-04 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_auto_20201204_1828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.user",
                verbose_name="user",
            ),
        ),
    ]
